# Dependencies
# - markdown:         redcarpet
highlighter:      rouge

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Douglas Beal"
tagline: ""
description: "Follow <a href=\"https://micro.blog/dougbeal\">@dougbeal on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/dougbeal\">@dougbeal on Micro.blog</a>."
baseurl: ""
url: "https://micro.dougbeal.com"
markdown: "kramdown"
username: "dougbeal"
microblog_user: "dougbeal"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Douglas Beal"
name: "Douglas Beal"
gravatar_hash: "264bb52db1a9563dd963816012316a7f"
avatar: "https://micro.blog/dougbeal/avatar.jpg"
full_name: "Douglas Beal"
bio: ""
twitter_username: "murderofcrows"
github_username: "dougbeal"
instagram_username: "murderofcro.ws"
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "430"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Douglas Beal"